spring.application.name=orcamento-automotivo
# Dados de Conexão (Senha como variável de ambiente)
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_orcamento?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# Estratégia de criação de tabelas
# 'update' cria as tabelas automaticamente baseadas nas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Dialeto para o MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Logs para ver o Spring criando as tabelas no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true